**Copyright: © NexStream Technical Education, LLC**.  
All rights reserved

**Chi-square Tests:**  

Note:  see Chi-square tests module for details on this question and the steps.  

Follow the assignment posted in the LMS and in the comments below for detailed steps.



In [1]:
#Chi-square summary: 
#   testStat = sum(observedCount-ExpectedCount)^2/ExpectedCount
#   P-value = look up or calc from ch-square dist with dof degrees of freedom
#   dof = (rows-1)x(cols-1)
#   expectedCount = total in row x total in col / overall total

from scipy.stats import chi2_contingency


#Calculate the test statistic, P-value, dof, expected counts
def calc_chiSquare(inTable):
  #inTable is input contingency table (initialized below)
  #return test statistic (float), p-value (float), degrees of freedom (int), expected count (table)
  ####Your code here...
  return chi2_contingency(inTable)


#Evaluate and state a conclusion
def interpret_chiSquareResults(prob, pval):
  #pval is the p-value
  #return the string 'Reject H0' or 'Fail to reject H0'
  ####Your code here...
 return 'Fail to reject H0' if(prob < pval) else 'Reject H0'


#-------------------------------------------------------------------------------------------------
#Test with the following doctest test vectors.
#DO NOT EDIT THE TEST CODE!!!!
#Even changing the spacing can cause errors.
#The test code will automatically execute when you run the cell.
#You should test all your combination of outputs but your code at least must pass these exact tests.
#If your code fails, you will see a description in the console cell.
#If your code passes, you will see the message: "TestResults(failed=0, attempted=X)" where X is the number of tests.

import doctest

#Contingency table from Chi-square test for Homogeneity - Example 2 Unit060
table = [[690, 1177, 702],
         [250,  242, 221],
         [ 40,   28,  50],
         [ 20,   13,  30]] 
print(table)

chiSqTestStat, Pvalue, DoF, expCount = calc_chiSquare(table)
print(expCount)
conclusion = interpret_chiSquareResults(0.95, Pvalue)

print('test statistic=%.2f, P-value=%.5f, DoF=%d' %(chiSqTestStat, Pvalue, DoF))
print('conclusion: ', conclusion)
"""
  >>> print('%.2f, %.5f, %d' %(chiSqTestStat, Pvalue, DoF))
  68.57, 0.00000, 6
  >>> print(expCount)
  [[ 741.84233324 1083.08980653  744.06786024]
   [ 205.89084609  300.60063529  206.50851863]
   [  34.07450188   49.74877274   34.17672538]
   [  18.1923188    26.56078545   18.24689576]]
  >>> print(conclusion)
  Reject H0
"""

doctest.testmod()


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/usr/lib/python3.8/doctest.py", line 1487, in run
    sys.settrace(save_trace)



[[690, 1177, 702], [250, 242, 221], [40, 28, 50], [20, 13, 30]]
[[ 741.84233324 1083.08980653  744.06786024]
 [ 205.89084609  300.60063529  206.50851863]
 [  34.07450188   49.74877274   34.17672538]
 [  18.1923188    26.56078545   18.24689576]]
test statistic=68.57, P-value=0.00000, DoF=6
conclusion:  Reject H0


TestResults(failed=0, attempted=3)